# Where are the worst food deserts?
### Let's analyze data from the U.S. Food and Drug Administration!

In [2]:
import pandas as pd
import numpy as np
import xlrd

<p>Let's load in our data.</p>
<p>Here's where we found it: https://www.ers.usda.gov/data-products/food-access-research-atlas/download-the-data/</p>
<p>(It's cool that this notebook won't recognize links!)</p>

In [137]:
tracts = pd.read_excel("data/DataDownload2015.xlsx", sheet_name = "Food Access Research Atlas", dtype = {"CensusTract": np.object})
tract_variables = pd.read_excel("data/DataDownload2015.xlsx", sheet_name = "Variable Lookup")

In [4]:
counties = pd.read_excel("data/DataDownload.xls", sheet_name = "ACCESS")
county_variables = pd.read_excel("data/DataDownload.xls", sheet_name = "Variable List")

In [138]:
tracts.head()

,CensusTract,State,County,Urban,POP2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
0,01001020100,Alabama,Autauga,1,1912,693,0,0,0.000000,0,...,221,1622,217,14,0,14,45,44,26,112
1,01001020200,Alabama,Autauga,1,2170,743,0,181,0.083410,0,...,214,888,1217,5,0,5,55,75,87,202
2,01001020300,Alabama,Autauga,1,3373,1256,0,0,0.000000,0,...,439,2576,647,17,5,11,117,87,108,120
3,01001020400,Alabama,Autauga,1,4386,1722,0,0,0.000000,0,...,904,4086,193,18,4,11,74,85,19,82
4,01001020500,Alabama,Autauga,1,10766,4082,0,181,0.016812,0,...,1126,8666,1437,296,9,48,310,355,198,488

In [139]:
counties.tail()

,FIPS,State,County,LACCESS_POP10,LACCESS_POP15,PCH_LACCESS_POP_10_15,PCT_LACCESS_POP10,PCT_LACCESS_POP15,LACCESS_LOWI10,LACCESS_LOWI15,...,PCT_LACCESS_HISP15,LACCESS_NHASIAN15,PCT_LACCESS_NHASIAN15,LACCESS_NHNA15,PCT_LACCESS_NHNA15,LACCESS_NHPI15,PCT_LACCESS_NHPI15,LACCESS_MULTIR15,PCT_LACCESS_MULTIR15,population
3138,56037,WY,Sweetwater,13391.715505,18934.737809,41.391428,30.570505,43.224074,2414.618816,4750.905615,...,6.075311,114.722086,0.261887,189.621441,0.432866,27.720443,0.063280,1605.391465,3.664775,43806.0
3139,56039,WY,Teton,6212.423697,6212.390430,-0.000535,29.174527,29.174370,1059.463554,1577.771012,...,3.457192,53.489780,0.251196,32.482255,0.152542,8.468847,0.039771,460.434464,2.162273,21294.0
3140,56041,WY,Uinta,4270.147119,4686.017653,9.739021,20.220414,22.189685,1518.415783,2054.179828,...,2.536304,13.831709,0.065497,40.339658,0.191020,6.586104,0.031187,350.320469,1.658871,21118.0
3141,56043,WY,Washakie,931.411647,931.411647,0.000000,10.915407,10.915407,233.628356,309.030331,...,0.415733,6.366775,0.074614,5.006976,0.058678,0.000000,0.000000,34.160542,0.400334,8533.0
3142,56045,WY,Weston,1240.493102,1237.267037,-0.260063,17.209949,17.165192,287.543111,302.697580,...,0.389472,2.771750,0.038454,10.372147,0.143898,0.507750,0.007044,24.811192,0.344217,7208.0

In [140]:
tracts.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72864 entries, 0 to 72863
Data columns (total 147 columns):
CensusTract             object
State                   object
County                  object
Urban                   int64
POP2010                 int64
OHU2010                 int64
GroupQuartersFlag       int64
NUMGQTRS                int64
PCTGQTRS                float64
LILATracts_1And10       int64
LILATracts_halfAnd10    int64
LILATracts_1And20       int64
LILATracts_Vehicle      int64
HUNVFlag                int64
LowIncomeTracts         int64
PovertyRate             float64
MedianFamilyIncome      int64
LA1and10                int64
LAhalfand10             int64
LA1and20                int64
LATracts_half           int64
LATracts1               int64
LATracts10              int64
LATracts20              int64
LATractsVehicle_20      int64
LAPOP1_10               float64
LAPOP05_10              float64
LAPOP1_20               float64
LALOWI1_10              float64
LALOWI05_10             float64
LALOWI1_20              float64
lapophalf               float64
lapophalfshare          float64
lalowihalf              float64
lalowihalfshare         float64
lakidshalf              float64
lakidshalfshare         float64
laseniorshalf           float64
laseniorshalfshare      float64
lawhitehalf             float64
lawhitehalfshare        float64
lablackhalf             float64
lablackhalfshare        float64
laasianhalf             float64
laasianhalfshare        float64
lanhopihalf             float64
lanhopihalfshare        float64
laaianhalf              float64
laaianhalfshare         float64
laomultirhalf           float64
laomultirhalfshare      float64
lahisphalf              float64
lahisphalfshare         float64
lahunvhalf              float64
lahunvhalfshare         float64
lasnaphalf              float64
lasnaphalfshare         float64
lapop1                  float64
lapop1share             float64
lalowi1                 float64
lalowi1share            float64
lakids1                 float64
lakids1share            float64
laseniors1              float64
laseniors1share         float64
lawhite1                float64
lawhite1share           float64
lablack1                float64
lablack1share           float64
laasian1                float64
laasian1share           float64
lanhopi1                float64
lanhopi1share           float64
laaian1                 float64
laaian1share            float64
laomultir1              float64
laomultir1share         float64
lahisp1                 float64
lahisp1share            float64
lahunv1                 float64
lahunv1share            float64
lasnap1                 float64
lasnap1share            float64
lapop10                 float64
lapop10share            float64
lalowi10                float64
lalowi10share           float64
lakids10                float64
lakids10share           float64
laseniors10             float64
laseniors10share        float64
lawhite10               float64
lawhite10share          float64
lablack10               float64
lablack10share          float64
laasian10               float64
laasian10share          float64
lanhopi10               float64
lanhopi10share          float64
laaian10                float64
laaian10share           float64
laomultir10             float64
laomultir10share        float64
lahisp10                float64
lahisp10share           float64
lahunv10                float64
lahunv10share           float64
lasnap10                float64
lasnap10share           float64
lapop20                 float64
lapop20share            float64
lalowi20                float64
lalowi20share           float64
lakids20                float64
lakids20share           float64
laseniors20             float64
laseniors20share        float64
lawhite20               float64
lawhite20share          float64
lablack20               float64
lablack20share          float64
laasian20               float64
laasian20share          float64
lanhopi20               float64
lanhopi20share          float64
laaian20                float64
laaian20share           float64
laomultir20             float64
laomultir20share        float64
lahisp20                float64
lahisp20share           float64
lahunv20                float64
lahunv20share           float64
lasnap20                float64
lasnap20share           float64
TractLOWI               int64
TractKids               int64
TractSeniors            int64
TractWhite              int64
TractBlack              int64
TractAsian              int64
TractNHOPI              int64
TractAIAN               int64
TractOMultir            int64
TractHispanic           int64
TractHUNV               int64
TractSNAP               int64
dtypes: float64(112), int64(32), object(3)
memory usage: 81.7+ MB

### Begin by working with county data
#### We will get to tracts later!

In [8]:
counties.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3143 entries, 0 to 3142
Data columns (total 44 columns):
FIPS                         3143 non-null int64
State                        3143 non-null object
County                       3143 non-null object
LACCESS_POP10                3143 non-null float64
LACCESS_POP15                3124 non-null float64
PCH_LACCESS_POP_10_15        3117 non-null float64
PCT_LACCESS_POP10            3143 non-null float64
PCT_LACCESS_POP15            3124 non-null float64
LACCESS_LOWI10               3143 non-null float64
LACCESS_LOWI15               3123 non-null float64
PCH_LACCESS_LOWI_10_15       3115 non-null float64
PCT_LACCESS_LOWI10           3143 non-null float64
PCT_LACCESS_LOWI15           3123 non-null float64
LACCESS_HHNV10               3143 non-null float64
LACCESS_HHNV15               3140 non-null float64
PCH_LACCESS_HHNV_10_15       3129 non-null float64
PCT_LACCESS_HHNV10           3143 non-null float64
PCT_LACCESS_HHNV15           3140 non-null float64
LACCESS_SNAP15               3123 non-null float64
PCT_LACCESS_SNAP15           3123 non-null float64
LACCESS_CHILD10              3143 non-null float64
LACCESS_CHILD15              3124 non-null float64
LACCESS_CHILD_10_15          3115 non-null float64
PCT_LACCESS_CHILD10          3143 non-null float64
PCT_LACCESS_CHILD15          3124 non-null float64
LACCESS_SENIORS10            3143 non-null float64
LACCESS_SENIORS15            3124 non-null float64
PCH_LACCESS_SENIORS_10_15    3117 non-null float64
PCT_LACCESS_SENIORS10        3143 non-null float64
PCT_LACCESS_SENIORS15        3124 non-null float64
LACCESS_WHITE15              3124 non-null float64
PCT_LACCESS_WHITE15          3124 non-null float64
LACCESS_BLACK15              3124 non-null float64
PCT_LACCESS_BLACK15          3124 non-null float64
LACCESS_HISP15               3124 non-null float64
PCT_LACCESS_HISP15           3124 non-null float64
LACCESS_NHASIAN15            3124 non-null float64
PCT_LACCESS_NHASIAN15        3124 non-null float64
LACCESS_NHNA15               3124 non-null float64
PCT_LACCESS_NHNA15           3124 non-null float64
LACCESS_NHPI15               3124 non-null float64
PCT_LACCESS_NHPI15           3124 non-null float64
LACCESS_MULTIR15             3124 non-null float64
PCT_LACCESS_MULTIR15         3124 non-null float64
dtypes: float64(41), int64(1), object(2)
memory usage: 1.1+ MB

In [12]:
counties.sort_values("PCT_LACCESS_POP15", ascending=False)

,FIPS,State,County,LACCESS_POP10,LACCESS_POP15,PCH_LACCESS_POP_10_15,PCT_LACCESS_POP10,PCT_LACCESS_POP15,LACCESS_LOWI10,LACCESS_LOWI15,...,LACCESS_HISP15,PCT_LACCESS_HISP15,LACCESS_NHASIAN15,PCT_LACCESS_NHASIAN15,LACCESS_NHNA15,PCT_LACCESS_NHNA15,LACCESS_NHPI15,PCT_LACCESS_NHPI15,LACCESS_MULTIR15,PCT_LACCESS_MULTIR15
1712,31117,NE,McPherson,539.000005,539.000005,0.000000e+00,100.000001,100.000001,136.427386,149.300471,...,2.000000,0.371058,0.0,0.000000,0.000000,0.000000,0.0,0.000000,8.000000,1.484230
1656,31005,NE,Arthur,460.000004,460.000004,0.000000e+00,100.000001,100.000001,167.370893,202.941179,...,19.000001,4.130435,1.0,0.217391,2.000000,0.434783,0.0,0.000000,18.000001,3.913044
72,2068,AK,Denali,1826.000014,1826.000014,0.000000e+00,100.000001,100.000001,338.312491,418.769635,...,42.000000,2.300110,19.0,1.040526,65.000000,3.559693,1.0,0.054765,94.000000,5.147864
567,16033,ID,Clark,982.000006,982.000006,0.000000e+00,100.000001,100.000001,588.970834,641.939249,...,398.000002,40.529532,5.0,0.509165,10.000000,1.018330,0.0,0.000000,249.000005,25.356416
1796,35003,NM,Catron,3725.000021,3725.000021,2.685756e-13,100.000001,100.000001,1664.513780,1693.913842,...,709.000006,19.033557,7.0,0.187919,99.000001,2.657718,0.0,0.000000,259.000001,6.953020
2864,51091,VA,Highland,2321.000012,2321.000012,0.000000e+00,100.000000,100.000000,706.699549,738.362185,...,18.000000,0.775528,4.0,0.172340,5.000000,0.215424,0.0,0.000000,17.000000,0.732443
1632,30069,MT,Petroleum,494.000002,494.000002,0.000000e+00,100.000000,100.000000,235.356904,195.160494,...,5.000000,1.012146,0.0,0.000000,0.000000,0.000000,0.0,0.000000,6.000000,1.214575
2738,48431,TX,Sterling,1143.000005,1143.000005,0.000000e+00,100.000000,100.000000,437.321740,540.137198,...,365.000002,31.933508,0.0,0.000000,23.000000,2.012248,0.0,0.000000,92.999999,8.136483
2600,48155,TX,Foard,1336.000005,1336.000005,0.000000e+00,100.000000,100.000000,708.099561,611.490654,...,187.000000,13.997006,5.0,0.374251,3.000000,0.224551,0.0,0.000000,64.000000,4.790419
1696,31085,NE,Hayes,967.000004,967.000004,0.000000e+00,100.000000,100.000000,315.100487,315.013975,...,33.000000,3.412616,3.0,0.310238,2.000000,0.206825,1.0,0.103413,22.000000,2.275078
1616,30037,MT,Golden Valley,884.000003,884.000003,0.000000e+00,100.000000,100.000000,349.824122,373.723578,...,31.000000,3.506787,6.0,0.678733,9.000000,1.018100,0.0,0.000000,38.000000,4.298643
1752,32011,NV,Eureka,1953.428926,1987.000007,1.718572e+00,98.310464,100.000000,494.958120,546.175854,...,238.000001,11.977856,18.0,0.905888,47.000000,2.365375,0.0,0.000000,145.000001,7.297433
275,8061,CO,Kiowa,1398.000005,1398.000005,0.000000e+00,100.000000,100.000000,498.175361,594.555748,...,78.000001,5.579399,0.0,0.000000,7.000000,0.500715,0.0,0.000000,41.000000,2.932761
987,20199,KS,Wallace,486.732735,1485.000005,2.050956e+02,32.776615,100.000000,181.799512,458.745280,...,108.000001,7.272727,1.0,0.067340,7.000000,0.471380,0.0,0.000000,80.000000,5.387205
2702,48359,TX,Oldham,2052.000006,2052.000006,0.000000e+00,100.000000,100.000000,824.215762,708.570609,...,243.000001,11.842105,17.0,0.828460,13.000000,0.633528,0.0,0.000000,110.000001,5.360624
2746,48447,TX,Throckmorton,1641.000004,1641.000004,0.000000e+00,100.000000,100.000000,577.257925,528.665614,...,152.000000,9.262645,7.0,0.426569,12.000000,0.731261,0.0,0.000000,56.000000,3.412553
2792,49031,UT,Piute,1556.000003,1556.000003,0.000000e+00,100.000000,100.000000,638.766843,733.987974,...,108.999999,7.005141,6.0,0.385604,5.000000,0.321337,2.0,0.128535,67.000000,4.305913
1637,30079,MT,Prairie,1179.000002,1179.000002,0.000000e+00,100.000000,100.000000,444.720111,440.484898,...,16.000000,1.357082,6.0,0.508906,2.000000,0.169635,0.0,0.000000,35.000000,2.968617
94,2282,AK,Yakutat,2.522153,662.000001,2.614742e+04,0.380990,100.000000,0.589698,167.845668,...,17.000000,2.567976,27.0,4.078550,236.999998,35.800604,12.0,1.812689,102.999999,15.558912
1661,31015,NE,Boyd,2099.000003,2099.000003,0.000000e+00,100.000000,100.000000,843.723873,865.272503,...,33.000000,1.572177,17.0,0.809909,12.000000,0.571701,2.0,0.095283,32.000000,1.524536
2414,46107,SD,Potter,2329.000003,2329.000003,0.000000e+00,100.000000,100.000000,748.256237,758.046097,...,17.000000,0.729927,8.0,0.343495,20.000000,0.858738,1.0,0.042937,25.000000,1.073422
2545,48045,TX,Briscoe,1637.000002,1637.000002,0.000000e+00,100.000000,100.000000,766.660082,781.575186,...,410.999998,25.106903,0.0,0.000000,3.000000,0.183262,0.0,0.000000,160.000000,9.773977
925,20075,KS,Hamilton,2690.000001,2690.000001,0.000000e+00,100.000000,100.000000,1284.692990,1112.415684,...,827.000001,30.743494,7.0,0.260223,33.000000,1.226766,3.0,0.111524,505.000001,18.773234
928,20081,KS,Haskell,4256.000002,4256.000002,0.000000e+00,100.000000,100.000000,1669.159512,1600.989099,...,1148.999999,26.997180,10.0,0.234962,28.000000,0.657895,0.0,0.000000,565.000001,13.275376
2397,46073,SD,Jerauld,2071.000001,2071.000001,0.000000e+00,100.000000,100.000000,875.104056,645.015626,...,84.000000,4.056012,4.0,0.193143,5.000000,0.241429,3.0,0.144858,49.000000,2.366007
2420,46119,SD,Sully,1373.000000,1373.000000,0.000000e+00,100.000000,100.000000,316.986650,242.168012,...,12.000000,0.873999,0.0,0.000000,16.000000,1.165331,0.0,0.000000,30.000000,2.184996
2395,46069,SD,Hyde,1412.223067,1420.000000,5.506873e-01,99.452329,100.000000,413.099385,270.516747,...,15.000001,1.056338,3.0,0.211268,120.000000,8.450704,1.0,0.070423,30.000000,2.112676
934,20093,KS,Kearny,350.213727,3977.000000,1.035592e+03,8.805978,100.000000,106.814050,1263.293357,...,1135.000002,28.539100,12.0,0.301735,39.000000,0.980639,1.0,0.025145,430.000001,10.812170
2539,48033,TX,Borden,641.000000,641.000000,1.596227e-13,100.000000,100.000000,178.434397,96.197623,...,95.000000,14.820593,1.0,0.156006,2.000000,0.312012,0.0,0.000000,38.000000,5.928237
1649,30103,MT,Treasure,718.000000,718.000000,0.000000e+00,100.000000,100.000000,286.689574,300.031540,...,25.000000,3.481894,3.0,0.417827,6.000000,0.835655,0.0,0.000000,35.000000,4.874652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1941,37103,NC,Jones,0.312788,0.312788,0.000000e+00,0.003081,0.003081,0.124719,0.144903,...,0.011171,0.000110,0.0,0.000000,0.004468,0.000044,0.0,0.000000,0.002234,0.000022
1858,36061,NY,New York,2.000000,2.000000,0.000000e+00,0.000126,0.000126,0.000000,0.000000,...,0.000000,0.000000,2.0,0.000126,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
1045,21105,KY,Hickman,159.003764,0.000000,-1.000000e+02,3.243651,0.000000,61.013072,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
1471,28141,MS,Tishomingo,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
2858,51079,VA,Greene,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
2876,51115,VA,Mathews,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
2456,47057,TN,Grainger,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
548,15005,HI,Kalawao,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
2881,51127,VA,New Kent,0.044135,0.000000,-1.000000e+02,0.000239,0.000000,0.011620,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
2735,48425,TX,Somervell,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
268,8047,CO,Gilpin,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
540,13311,GA,White,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
612,17035,IL,Cumberland,91.845746,NaN,NaN,0.831334,NaN,16.187373,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
754,18115,IN,Ohio,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
777,18161,IN,Union,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1031,21077,KY,Gallatin,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1059,21133,KY,Letcher,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1100,21215,KY,Spencer,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1240,26019,MI,Benzie,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1416,28031,MS,Covington,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1929,37079,NC,Greene,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1950,37121,NC,Mitchell,862.113229,NaN,NaN,5.533816,NaN,397.708173,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2512,47169,TN,Trousdale,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2712,48379,TX,Rains,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2833,51027,VA,Buchanan,1356.810559,NaN,NaN,5.630387,NaN,688.581021,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2845,51051,VA,Dickenson,30.107920,NaN,NaN,0.189322,NaN,17.615772,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2868,51099,VA,King George,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2915,51510,VA,Alexandria,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2926,51610,VA,Falls Church,165.877687,NaN,NaN,1.345100,NaN,10.226877,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3094,55091,WI,Pepin,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<p>So, I need to do some quick math to figure out population, instead of loading another dumb excel file in.</p>

In [14]:
counties["population"] = counties["LACCESS_POP15"] /(counties["PCT_LACCESS_POP15"]/100)

In [15]:
counties_sorted_pop = counties.sort_values("population", ascending=False)
counties_sorted_pop.head(5)

,FIPS,State,County,LACCESS_POP10,LACCESS_POP15,PCH_LACCESS_POP_10_15,PCT_LACCESS_POP10,PCT_LACCESS_POP15,LACCESS_LOWI10,LACCESS_LOWI15,...,PCT_LACCESS_HISP15,LACCESS_NHASIAN15,PCT_LACCESS_NHASIAN15,LACCESS_NHNA15,PCT_LACCESS_NHNA15,LACCESS_NHPI15,PCT_LACCESS_NHPI15,LACCESS_MULTIR15,PCT_LACCESS_MULTIR15,population
204,6037,CA,Los Angeles,613459.048964,622625.436181,1.494213,6.247925,6.341282,139368.943118,161790.521343,...,2.214779,76998.348562,0.784209,3943.964203,0.040168,1399.535435,0.014254,115781.021513,1.179200,9818605.0
610,17031,IL,Cook,415199.839259,373742.394052,-9.984938,7.992797,7.194721,91537.324125,88306.588509,...,0.806436,29637.535941,0.570537,977.220314,0.018812,75.759928,0.001458,22562.511214,0.434339,5194675.0
2623,48201,TX,Harris,886068.668386,740267.412661,-16.454848,21.651253,18.088572,292541.789025,259479.516033,...,6.437218,40101.958015,0.979899,4714.186116,0.115192,690.306606,0.016868,113699.486121,2.778268,4092459.0
103,4013,AZ,Maricopa,492281.154146,511215.572448,3.846261,12.896674,13.392714,139988.257834,167933.017109,...,3.381186,14730.523043,0.385907,10079.040365,0.264049,724.064859,0.018969,73145.345007,1.916246,3817117.0
222,6073,CA,San Diego,456713.537412,424210.884923,-7.116639,14.755003,13.704943,84421.134866,95163.546058,...,2.415206,40484.619297,1.307933,3034.525144,0.098036,1751.033341,0.056570,45842.152590,1.481018,3095313.0

<p>Looks like it worked.<p>

In [102]:
counties_sorted_food_access = counties.sort_values("PCT_LACCESS_LOWI15", ascending=False)
counties_sorted_food_access.head(5)

,FIPS,State,County,LACCESS_POP10,LACCESS_POP15,PCH_LACCESS_POP_10_15,PCT_LACCESS_POP10,PCT_LACCESS_POP15,LACCESS_LOWI10,LACCESS_LOWI15,...,PCT_LACCESS_HISP15,LACCESS_NHASIAN15,PCT_LACCESS_NHASIAN15,LACCESS_NHNA15,PCT_LACCESS_NHNA15,LACCESS_NHPI15,PCT_LACCESS_NHPI15,LACCESS_MULTIR15,PCT_LACCESS_MULTIR15,population
2369,46017,SD,Buffalo,350.859579,1906.678707,443.430712,18.350396,99.721690,221.743535,1373.661281,...,1.830544,1.000000,0.052301,1603.101301,83.844210,0.0,0.000000,17.000000,0.889121,1912.0
2637,48229,TX,Hudspeth,3473.342355,3462.921017,-0.300038,99.923543,99.623735,2512.260093,2338.157618,...,79.323968,16.000000,0.460299,37.999999,1.093211,0.0,0.000000,633.826775,18.234372,3476.0
567,16033,ID,Clark,982.000006,982.000006,0.000000,100.000001,100.000001,588.970834,641.939249,...,40.529532,5.000000,0.509165,10.000000,1.018330,0.0,0.000000,249.000005,25.356416,982.0
2417,46113,SD,Shannon,6478.169436,10779.636539,66.399423,47.682684,79.343711,5089.355448,8438.376428,...,1.474038,9.999999,0.073605,10348.138341,76.167660,2.0,0.014721,105.328370,0.775271,13586.0
2364,46007,SD,Bennett,3319.803232,3319.803232,0.000000,96.759057,96.759057,1693.369893,2035.777593,...,1.948373,13.000000,0.378898,2005.381053,58.448879,3.0,0.087438,139.872960,4.076740,3431.0

<p>Now we'll look at food insecurity in the top decile of U.S. counties.</p>
<p>We can tweak this later if we want to look at the top quartile, and reuse this process to look at large census tracts (though, if you understand census tracts, won't really mean much.)</p>

In [103]:
counties_sorted_food_access_top_10_poppercent = counties_sorted_food_access["population"].quantile(q=0.9)

In [104]:
big_counties = counties_sorted_food_access[counties_sorted_food_access["population"] >= counties_sorted_food_access_top_10_poppercent]

In [105]:
big_counties.head(5)

,FIPS,State,County,LACCESS_POP10,LACCESS_POP15,PCH_LACCESS_POP_10_15,PCT_LACCESS_POP10,PCT_LACCESS_POP15,LACCESS_LOWI10,LACCESS_LOWI15,...,PCT_LACCESS_HISP15,LACCESS_NHASIAN15,PCT_LACCESS_NHASIAN15,LACCESS_NHNA15,PCT_LACCESS_NHNA15,LACCESS_NHPI15,PCT_LACCESS_NHPI15,LACCESS_MULTIR15,PCT_LACCESS_MULTIR15,population
2630,48215,TX,Hidalgo,330465.695700,269110.460682,-18.566295,42.653448,34.734283,205710.972505,164640.597158,...,31.786765,1740.417095,0.224637,749.881976,0.096788,27.222979,0.003514,22166.516930,2.861049,774769.0
2677,48309,TX,McLennan,66738.901183,91765.194616,37.498810,28.410897,39.064645,29367.125244,47389.049626,...,9.988829,1624.452964,0.691533,591.157321,0.251657,32.210454,0.013712,13185.741053,5.613199,234906.0
104,4015,AZ,Mohave,88373.508832,88341.577129,-0.036133,44.145699,44.129748,34539.671598,40061.481981,...,5.874096,769.304758,0.384295,1751.832051,0.875102,147.264868,0.073564,6700.216554,3.346996,200186.0
1802,35013,NM,DoÃ±a Ana,88229.556460,82862.819241,-6.082698,42.168088,39.603131,43781.861123,40779.494089,...,26.758744,616.439601,0.294619,1059.839321,0.506535,72.889647,0.034837,17921.233977,8.565204,209233.0
507,13245,GA,Richmond,67308.091408,78927.441194,17.262932,33.561918,39.355689,25075.372507,35981.293002,...,1.986700,1384.214326,0.690213,287.255788,0.143235,225.863587,0.112623,3523.814109,1.757084,200549.0

<p>Now let's just look at the columns we need then output the data for Lisa!</p>

In [106]:
final_counties = big_counties[["State", "County", "PCT_LACCESS_LOWI15"]]

In [107]:
final_counties.rename(columns={"PCT_LACCESS_LOWI15": "percent_without_grocery_access"}).head()

     State    County  percent_without_grocery_access
2630    TX   Hidalgo                       21.250282
2677    TX  McLennan                       20.173622
104     AZ    Mohave                       20.012130
1802    NM  DoÃ±a Ana                       19.489992
507     GA  Richmond                       17.941397

In [108]:
final_counties = final_counties.rename(columns={"PCT_LACCESS_POP15": "percent_without_grocery_access"})

In [109]:
len(final_counties)

312

In [110]:
final_counties.to_csv("output/final_counties.csv")

<p>Not quite finished, let's do all this except with Florida.</p>

In [111]:
florida_counties = counties_sorted_food_access[counties_sorted_food_access["State"] == "FL"]

In [112]:
len(florida_counties)

67

In [113]:
florida_counties = florida_counties[["State", "County", "PCT_LACCESS_LOWI15"]]

In [114]:
florida_counties = florida_counties.rename(columns={"PCT_LACCESS_LOWI15": "percent_without_grocery_access"})

In [115]:
florida_counties.to_csv("output/final_florida_counties.csv")

### Now let's do some similar analyses for Census tracts

In [129]:
tract_variables.head(50)

<bound method DataFrame.info of                     Field                                           LongName  \
0             CensusTract                                       Census tract
1                   State                                              State
2                  County                                             County
3                   Urban                                        Urban tract
4                 POP2010                            Population, tract total
5                 OHU2010                               Housing units, total
6       GroupQuartersFlag              Group quarters, tract with high share
7                NUMGQTRS  Group quarters, tract population residing in, ...
8                PCTGQTRS  Group quarters, tract population residing in, ...
9       LILATracts_1And10  Low income and low access tract measured at 1 ...
10   LILATracts_halfAnd10  Low income and low access tract measured at 1/...
11      LILATracts_1And20  Low income and low access tract measured at 1 ...
12     LILATracts_Vehicle  Low income and low access tract using vehicle ...
13               HUNVFlag      Vehicle access, tract with low vehicle access
14        LowIncomeTracts                                   Low income tract
15            PovertyRate                                 Tract poverty rate
16     MedianFamilyIncome                         Tract median family income
17               LA1and10  Low access tract at 1 mile for urban areas and...
18            LAhalfand10  Low access tract at 1/2 mile for urban areas a...
19               LA1and20  Low access tract at 1 mile for urban areas and...
20          LATracts_half                       Low access tract at 1/2 mile
21              LATracts1                         Low access tract at 1 mile
22             LATracts10                       Low access tract at 10 miles
23             LATracts20                       Low access tract at 20 miles
24     LATractsVehicle_20  Low access tract using vehicle access and at 2...
25              LAPOP1_10  Low access, population at 1 mile for urban are...
26             LAPOP05_10  Low access, population at 1/2 mile for urban a...
27              LAPOP1_20  Low access, population at 1 mile for urban are...
28             LALOWI1_10  Low access, low-income population at 1 mile fo...
29            LALOWI05_10  Low access, low-income population at 1/2 mile ...
..                    ...                                                ...
117             lawhite20   Low access, White population at 20 miles, number
118        lawhite20share    Low access, White population at 20 miles, share
119             lablack20  Low access, Black or African American populati...
120        lablack20share  Low access, Black or African American populati...
121             laasian20   Low access, Asian population at 20 miles, number
122        laasian20share    Low access, Asian population at 20 miles, share
123             lanhopi20  Low access, Native Hawaiian and Other Pacific ...
124        lanhopi20share  Low access, Native Hawaiian and Other Pacific ...
125              laaian20  Low access, American Indian and Alaska Native ...
126         laaian20share  Low access, American Indian and Alaska Native ...
127           laomultir20  Low access, Other/Multiple race population at ...
128      laomultir20share  Low access, Other/Multiple race population at ...
129              lahisp20  Low access, Hispanic or Latino population at 2...
130         lahisp20share  Low access, Hispanic or Latino population at 2...
131              lahunv20  Vehicle access, housing units without and low ...
132         lahunv20share  Vehicle access, housing units without and low ...
133              lasnap20  Low access, housing units receiving SNAP benef...
134         lasnap20share  Low access, housing units receiving SNAP benef...
135             TractLOWI                Tract low-income population, number
136             TractKids                    Tract children age 0-17, number
137          TractSeniors                      Tract seniors age 65+, number
138            TractWhite                     Tract White population, number
139            TractBlack  Tract Black or African American population, nu...
140            TractAsian                     Tract Asian population, number
141            TractNHOPI  Tract Native Hawaiian and Other Pacific Island...
142             TractAIAN  Tract American Indian and Alaska Native popula...
143          TractOMultir       Tract Other/Multiple race population, number
144         TractHispanic        Tract Hispanic or Latino population, number
145             TractHUNV      Tract housing units without a vehicle, number
146             TractSNAP  Tract housing units receiving SNAP benefits, n...

                                           Description
0                                  Census tract number
1                                           State name
2                                          County name
3                                 Flag for urban tract
4                    Population count from 2010 census
5         Occupied housing unit count from 2010 census
6                           Flag for tract where >=67%
7    Count of tract population residing in group qu...
8    Percent of tract population residing in group ...
9    Flag for food desert when considering low acce...
10   Flag for food desert when considering low acce...
11   Flag for food desert when considering low acce...
12   Flag for food desert when considering vehicle ...
13   Flag for tract where >= 100 of households do n...
14                           Flag for low income tract
15   Share of the tract population living with inco...
16                          Tract median family income
17   Flag for low access tract at 1 mile for urban ...
18   Flag for low access tract at 1/2 mile for urba...
19   Flag for low access tract at 1 mile for urban ...
20   Flag for low access tract when considering 1/2...
21   Flag for low access tract when considering 1 m...
22   Flag for low access tract when considering 10 ...
23   Flag for low access tract when considering 20 ...
24   Flag for tract where >= 100 of households do n...
25   Population count beyond 1 mile for urban areas...
26   Population count beyond 1/2 mile for urban are...
27   Population count beyond 1 mile for urban areas...
28   Low income population count beyond 1 mile for ...
29   Low income population count beyond 1/2 mile fo...
..                                                 ...
117  White population count beyond 20 miles from su...
118  Share of tract population that are white beyon...
119  Black or African American population count bey...
120  Share of tract population that are Black or Af...
121  Asian population count beyond 20 miles from su...
122  Share of tract population that are Asian beyon...
123  Native Hawaiian or Other Pacific Islander popu...
124  Share of tract population that are Native Hawa...
125  American Indian or Alaska Native population co...
126  Share of tract population that are American In...
127  Other/Multiple race population count beyond 20...
128  Share of tract population that are Other/Multi...
129  Hispanic or Latino ethnicity population count ...
130  Share of tract population that are of Hispanic...
131  Housing units without vehicle count beyond 20 ...
132  Share of tract housing units that are without ...
133  Housing units receiving SNAP benefits count be...
134  Share of tract housing units receiving SNAP be...
135     Total count of low-income population in tract
136         Total count of children age 0-17 in tract
137           Total count of seniors age 65+ in tract
138          Total count of White population in tract
139  Total count of Black or African American popul...
140          Total count of Asian population in tract
141  Total count of Native Hawaiian and Other Pacif...
142  Total count of American Indian and Alaska Nati...
143  Total count of Other/Multiple race population ...
144  Total count of Hispanic or Latino population i...
145  Total count of housing units without a vehicle...
146  Total count of housing units receiving SNAP be...

[147 rows x 3 columns]>

In [141]:
urban_tracts = tracts[tracts["Urban"] == 1]
rural_tracts = tracts[tracts["Urban"] == 0]

In [142]:
urban_tracts = urban_tracts[["CensusTract", "State", "County", "lalowi1", "lalowi1share"]]

In [143]:
urban_tracts = urban_tracts.sort_values("lalowi1", ascending=False)

In [144]:
rural_tracts = rural_tracts[["CensusTract", "State", "County", "lalowi10", "lalowi10share"]]

In [145]:
rural_tracts = rural_tracts.sort_values("lalowi10", ascending=False)

In [146]:
florida_urban_tracts = urban_tracts[urban_tracts["State"] == "Florida"]

In [147]:
florida_urban_tracts.head()

       CensusTract    State      County       lalowi1  lalowi1share
16917  12097041100  Florida     Osceola  10249.292943      0.609098
18028  12115002712  Florida    Sarasota   9863.641301      0.298527
17743  12105012503  Florida        Polk   7341.399048      0.470181
16503  12086011401  Florida  Miami-Dade   5246.284453      0.340956
14815  12021010802  Florida     Collier   5046.766527      0.494393

In [148]:
florida_rural_tracts = rural_tracts[rural_tracts["State"] == "Florida"]

In [149]:
florida_rural_tracts.head()

       CensusTract    State      County     lalowi10  lalowi10share
18292  12133970302  Florida  Washington  3880.645124       0.586643
14138  12003040201  Florida       Baker  2069.537576       0.275241
16691  12093910102  Florida  Okeechobee  1756.285562       0.622576
18232  12127090102  Florida     Volusia  1723.073332       0.496134
15141  12043000200  Florida      Glades  1706.067179       0.248336

In [150]:
rural_tracts = rural_tracts.rename(columns={"lalowi10": "pop_with_low_access", "lalowi10share": "percent_with_low_access"})
urban_tracts = urban_tracts.rename(columns={"lalowi1": "pop_with_low_access", "lalowi1share": "percent_with_low_access"})
florida_rural_tracts = florida_rural_tracts.rename(columns={"lalowi10": "pop_with_low_access", "lalowi10share": "percent_with_low_access"})
florida_urban_tracts = florida_urban_tracts.rename(columns={"lalowi1": "pop_with_low_access", "lalowi1share": "percent_with_low_access"})

In [152]:
rural_tracts.to_csv("output/final_rural_tracts.csv")
urban_tracts.to_csv("output/final_urban_tracts.csv")
florida_rural_tracts.to_csv("output/final_florida_rural_tracts.csv")
florida_urban_tracts.to_csv("output/final_florida_urban_tracts.csv")

,CensusTract,State,County,pop_with_low_access,percent_with_low_access
1237,02050000100,Alaska,Bethel,6012.955671,0.634077
1352,04001944300,Arizona,Apache,4458.604334,0.640788
1349,04001944100,Arizona,Apache,4401.402687,0.749813
42864,35031946000,New Mexico,McKinley,4211.904713,0.741924
1347,04001942700,Arizona,Apache,4064.794212,0.722245
18292,12133970302,Florida,Washington,3880.645124,0.586643
1437,04007940400,Arizona,Gila,3694.188944,0.698599
4515,06025012302,California,Imperial,3680.530406,0.773871
1438,04009940500,Arizona,Graham,3635.739312,0.760615
1319,02180000100,Alaska,Nome,3611.882224,0.630896
1354,04001944902,Arizona,Apache,3593.833596,0.740539
4514,06025012301,California,Imperial,3496.933517,0.620794
42956,35045942900,New Mexico,San Juan,3491.375880,0.708334
42854,35031943800,New Mexico,McKinley,3354.973142,0.536538
64746,48225950700,Texas,Houston,3326.481431,0.655335
42852,35031943600,New Mexico,McKinley,3234.261834,0.553244
59947,46113940800,South Dakota,Shannon,3176.597173,0.669462
2424,04017940015,Arizona,Navajo,3131.605715,0.749906
1339,02270000100,Alaska,Wade Hampton,3120.823723,0.418397
68403,51135000300,Virginia,Nottoway,3118.275853,0.441432
37292,28135950300,Mississippi,Tallahatchie,3113.494074,0.570341
2687,04019940800,Arizona,Pima,3072.489223,0.688590
2285,04013723306,Arizona,Maricopa,3041.416737,0.578326
37283,28133950100,Mississippi,Sunflower,2961.765385,0.396382
29364,22125951701,Louisiana,West Feliciana,2929.104594,0.354099
1353,04001944901,Arizona,Apache,2868.952353,0.713492
38971,30085940002,Montana,Roosevelt,2774.769823,0.645596
2381,04015950600,Arizona,Mohave,2764.686655,0.306201
1417,04005942202,Arizona,Coconino,2761.651033,0.724272
36772,28027950100,Mississippi,Coahoma,2681.375787,0.656556
...,...,...,...,...,...
34031,26123971100,Michigan,Newaygo,0.000000,0.000000
34032,26123971200,Michigan,Newaygo,0.000000,0.000000
34033,26125120000,Michigan,Oakland,0.000000,0.000000
34034,26125120300,Michigan,Oakland,0.000000,0.000000
33979,26119910500,Michigan,Montmorency,0.000000,0.000000
33978,26119910400,Michigan,Montmorency,0.000000,0.000000
33974,26117971300,Michigan,Montcalm,0.000000,0.000000
33972,26117971100,Michigan,Montcalm,0.000000,0.000000
33948,26115832600,Michigan,Monroe,0.000000,0.000000
33949,26115832700,Michigan,Monroe,0.000000,0.000000
33950,26115832800,Michigan,Monroe,0.000000,0.000000
33951,26115832900,Michigan,Monroe,0.000000,0.000000
33952,26115833000,Michigan,Monroe,0.000000,0.000000
33953,26115833100,Michigan,Monroe,0.000000,0.000000
33954,26115833200,Michigan,Monroe,0.000000,0.000000
33956,26115833500,Michigan,Monroe,0.000000,0.000000
33957,26115833600,Michigan,Monroe,0.000000,0.000000
33958,26115833700,Michigan,Monroe,0.000000,0.000000
33961,26115990000,Michigan,Monroe,0.000000,0.000000
33962,26117970100,Michigan,Montcalm,0.000000,0.000000
33963,26117970200,Michigan,Montcalm,0.000000,0.000000
33964,26117970300,Michigan,Montcalm,0.000000,0.000000
33965,26117970400,Michigan,Montcalm,0.000000,0.000000
33966,26117970500,Michigan,Montcalm,0.000000,0.000000
33967,26117970600,Michigan,Montcalm,0.000000,0.000000
33968,26117970700,Michigan,Montcalm,0.000000,0.000000
33969,26117970800,Michigan,Montcalm,0.000000,0.000000
33970,26117970900,Michigan,Montcalm,0.000000,0.000000
33971,26117971000,Michigan,Montcalm,0.000000,0.000000
38651,29225470301,Missouri,Webster,0.000000,0.000000