# Where are the worst food deserts?
### Let's analyze data from the U.S. Food and Drug Administration!

In [2]:
import pandas as pd
import numpy as np
import xlrd

<p>Let's load in our data.</p>
<p>Here's where we found it: https://www.ers.usda.gov/data-products/food-access-research-atlas/download-the-data/</p>
<p>(It's cool that this notebook won't recognize links!)</p>

In [3]:
tracts = pd.read_excel("data/DataDownload2015.xlsx", sheet_name = "Food Access Research Atlas")
tract_variables = pd.read_excel("data/DataDownload2015.xlsx", sheet_name = "Variable Lookup")

In [4]:
counties = pd.read_excel("data/DataDownload.xls", sheet_name = "ACCESS")
county_variables = pd.read_excel("data/DataDownload.xls", sheet_name = "Variable List")

In [5]:
tracts.head()

,CensusTract,State,County,Urban,POP2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
0,1001020100,Alabama,Autauga,1,1912,693,0,0,0.000000,0,...,221,1622,217,14,0,14,45,44,26,112
1,1001020200,Alabama,Autauga,1,2170,743,0,181,0.083410,0,...,214,888,1217,5,0,5,55,75,87,202
2,1001020300,Alabama,Autauga,1,3373,1256,0,0,0.000000,0,...,439,2576,647,17,5,11,117,87,108,120
3,1001020400,Alabama,Autauga,1,4386,1722,0,0,0.000000,0,...,904,4086,193,18,4,11,74,85,19,82
4,1001020500,Alabama,Autauga,1,10766,4082,0,181,0.016812,0,...,1126,8666,1437,296,9,48,310,355,198,488

In [6]:
counties.tail()

,FIPS,State,County,LACCESS_POP10,LACCESS_POP15,PCH_LACCESS_POP_10_15,PCT_LACCESS_POP10,PCT_LACCESS_POP15,LACCESS_LOWI10,LACCESS_LOWI15,...,LACCESS_HISP15,PCT_LACCESS_HISP15,LACCESS_NHASIAN15,PCT_LACCESS_NHASIAN15,LACCESS_NHNA15,PCT_LACCESS_NHNA15,LACCESS_NHPI15,PCT_LACCESS_NHPI15,LACCESS_MULTIR15,PCT_LACCESS_MULTIR15
3138,56037,WY,Sweetwater,13391.715505,18934.737809,41.391428,30.570505,43.224074,2414.618816,4750.905615,...,2661.350520,6.075311,114.722086,0.261887,189.621441,0.432866,27.720443,0.063280,1605.391465,3.664775
3139,56039,WY,Teton,6212.423697,6212.390430,-0.000535,29.174527,29.174370,1059.463554,1577.771012,...,736.174507,3.457192,53.489780,0.251196,32.482255,0.152542,8.468847,0.039771,460.434464,2.162273
3140,56041,WY,Uinta,4270.147119,4686.017653,9.739021,20.220414,22.189685,1518.415783,2054.179828,...,535.616715,2.536304,13.831709,0.065497,40.339658,0.191020,6.586104,0.031187,350.320469,1.658871
3141,56043,WY,Washakie,931.411647,931.411647,0.000000,10.915407,10.915407,233.628356,309.030331,...,35.474502,0.415733,6.366775,0.074614,5.006976,0.058678,0.000000,0.000000,34.160542,0.400334
3142,56045,WY,Weston,1240.493102,1237.267037,-0.260063,17.209949,17.165192,287.543111,302.697580,...,28.073114,0.389472,2.771750,0.038454,10.372147,0.143898,0.507750,0.007044,24.811192,0.344217

In [7]:
tracts.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72864 entries, 0 to 72863
Data columns (total 147 columns):
CensusTract             int64
State                   object
County                  object
Urban                   int64
POP2010                 int64
OHU2010                 int64
GroupQuartersFlag       int64
NUMGQTRS                int64
PCTGQTRS                float64
LILATracts_1And10       int64
LILATracts_halfAnd10    int64
LILATracts_1And20       int64
LILATracts_Vehicle      int64
HUNVFlag                int64
LowIncomeTracts         int64
PovertyRate             float64
MedianFamilyIncome      int64
LA1and10                int64
LAhalfand10             int64
LA1and20                int64
LATracts_half           int64
LATracts1               int64
LATracts10              int64
LATracts20              int64
LATractsVehicle_20      int64
LAPOP1_10               float64
LAPOP05_10              float64
LAPOP1_20               float64
LALOWI1_10              float64
LALOWI05_10             float64
LALOWI1_20              float64
lapophalf               float64
lapophalfshare          float64
lalowihalf              float64
lalowihalfshare         float64
lakidshalf              float64
lakidshalfshare         float64
laseniorshalf           float64
laseniorshalfshare      float64
lawhitehalf             float64
lawhitehalfshare        float64
lablackhalf             float64
lablackhalfshare        float64
laasianhalf             float64
laasianhalfshare        float64
lanhopihalf             float64
lanhopihalfshare        float64
laaianhalf              float64
laaianhalfshare         float64
laomultirhalf           float64
laomultirhalfshare      float64
lahisphalf              float64
lahisphalfshare         float64
lahunvhalf              float64
lahunvhalfshare         float64
lasnaphalf              float64
lasnaphalfshare         float64
lapop1                  float64
lapop1share             float64
lalowi1                 float64
lalowi1share            float64
lakids1                 float64
lakids1share            float64
laseniors1              float64
laseniors1share         float64
lawhite1                float64
lawhite1share           float64
lablack1                float64
lablack1share           float64
laasian1                float64
laasian1share           float64
lanhopi1                float64
lanhopi1share           float64
laaian1                 float64
laaian1share            float64
laomultir1              float64
laomultir1share         float64
lahisp1                 float64
lahisp1share            float64
lahunv1                 float64
lahunv1share            float64
lasnap1                 float64
lasnap1share            float64
lapop10                 float64
lapop10share            float64
lalowi10                float64
lalowi10share           float64
lakids10                float64
lakids10share           float64
laseniors10             float64
laseniors10share        float64
lawhite10               float64
lawhite10share          float64
lablack10               float64
lablack10share          float64
laasian10               float64
laasian10share          float64
lanhopi10               float64
lanhopi10share          float64
laaian10                float64
laaian10share           float64
laomultir10             float64
laomultir10share        float64
lahisp10                float64
lahisp10share           float64
lahunv10                float64
lahunv10share           float64
lasnap10                float64
lasnap10share           float64
lapop20                 float64
lapop20share            float64
lalowi20                float64
lalowi20share           float64
lakids20                float64
lakids20share           float64
laseniors20             float64
laseniors20share        float64
lawhite20               float64
lawhite20share          float64
lablack20               float64
lablack20share          float64
laasian20               float64
laasian20share          float64
lanhopi20               float64
lanhopi20share          float64
laaian20                float64
laaian20share           float64
laomultir20             float64
laomultir20share        float64
lahisp20                float64
lahisp20share           float64
lahunv20                float64
lahunv20share           float64
lasnap20                float64
lasnap20share           float64
TractLOWI               int64
TractKids               int64
TractSeniors            int64
TractWhite              int64
TractBlack              int64
TractAsian              int64
TractNHOPI              int64
TractAIAN               int64
TractOMultir            int64
TractHispanic           int64
TractHUNV               int64
TractSNAP               int64
dtypes: float64(112), int64(33), object(2)
memory usage: 81.7+ MB

### Begin by working with county data
#### We will get to tracts later!

In [8]:
counties.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3143 entries, 0 to 3142
Data columns (total 44 columns):
FIPS                         3143 non-null int64
State                        3143 non-null object
County                       3143 non-null object
LACCESS_POP10                3143 non-null float64
LACCESS_POP15                3124 non-null float64
PCH_LACCESS_POP_10_15        3117 non-null float64
PCT_LACCESS_POP10            3143 non-null float64
PCT_LACCESS_POP15            3124 non-null float64
LACCESS_LOWI10               3143 non-null float64
LACCESS_LOWI15               3123 non-null float64
PCH_LACCESS_LOWI_10_15       3115 non-null float64
PCT_LACCESS_LOWI10           3143 non-null float64
PCT_LACCESS_LOWI15           3123 non-null float64
LACCESS_HHNV10               3143 non-null float64
LACCESS_HHNV15               3140 non-null float64
PCH_LACCESS_HHNV_10_15       3129 non-null float64
PCT_LACCESS_HHNV10           3143 non-null float64
PCT_LACCESS_HHNV15           3140 non-null float64
LACCESS_SNAP15               3123 non-null float64
PCT_LACCESS_SNAP15           3123 non-null float64
LACCESS_CHILD10              3143 non-null float64
LACCESS_CHILD15              3124 non-null float64
LACCESS_CHILD_10_15          3115 non-null float64
PCT_LACCESS_CHILD10          3143 non-null float64
PCT_LACCESS_CHILD15          3124 non-null float64
LACCESS_SENIORS10            3143 non-null float64
LACCESS_SENIORS15            3124 non-null float64
PCH_LACCESS_SENIORS_10_15    3117 non-null float64
PCT_LACCESS_SENIORS10        3143 non-null float64
PCT_LACCESS_SENIORS15        3124 non-null float64
LACCESS_WHITE15              3124 non-null float64
PCT_LACCESS_WHITE15          3124 non-null float64
LACCESS_BLACK15              3124 non-null float64
PCT_LACCESS_BLACK15          3124 non-null float64
LACCESS_HISP15               3124 non-null float64
PCT_LACCESS_HISP15           3124 non-null float64
LACCESS_NHASIAN15            3124 non-null float64
PCT_LACCESS_NHASIAN15        3124 non-null float64
LACCESS_NHNA15               3124 non-null float64
PCT_LACCESS_NHNA15           3124 non-null float64
LACCESS_NHPI15               3124 non-null float64
PCT_LACCESS_NHPI15           3124 non-null float64
LACCESS_MULTIR15             3124 non-null float64
PCT_LACCESS_MULTIR15         3124 non-null float64
dtypes: float64(41), int64(1), object(2)
memory usage: 1.1+ MB

In [12]:
counties.sort_values("PCT_LACCESS_POP15", ascending=False)

,FIPS,State,County,LACCESS_POP10,LACCESS_POP15,PCH_LACCESS_POP_10_15,PCT_LACCESS_POP10,PCT_LACCESS_POP15,LACCESS_LOWI10,LACCESS_LOWI15,...,LACCESS_HISP15,PCT_LACCESS_HISP15,LACCESS_NHASIAN15,PCT_LACCESS_NHASIAN15,LACCESS_NHNA15,PCT_LACCESS_NHNA15,LACCESS_NHPI15,PCT_LACCESS_NHPI15,LACCESS_MULTIR15,PCT_LACCESS_MULTIR15
1712,31117,NE,McPherson,539.000005,539.000005,0.000000e+00,100.000001,100.000001,136.427386,149.300471,...,2.000000,0.371058,0.0,0.000000,0.000000,0.000000,0.0,0.000000,8.000000,1.484230
1656,31005,NE,Arthur,460.000004,460.000004,0.000000e+00,100.000001,100.000001,167.370893,202.941179,...,19.000001,4.130435,1.0,0.217391,2.000000,0.434783,0.0,0.000000,18.000001,3.913044
72,2068,AK,Denali,1826.000014,1826.000014,0.000000e+00,100.000001,100.000001,338.312491,418.769635,...,42.000000,2.300110,19.0,1.040526,65.000000,3.559693,1.0,0.054765,94.000000,5.147864
567,16033,ID,Clark,982.000006,982.000006,0.000000e+00,100.000001,100.000001,588.970834,641.939249,...,398.000002,40.529532,5.0,0.509165,10.000000,1.018330,0.0,0.000000,249.000005,25.356416
1796,35003,NM,Catron,3725.000021,3725.000021,2.685756e-13,100.000001,100.000001,1664.513780,1693.913842,...,709.000006,19.033557,7.0,0.187919,99.000001,2.657718,0.0,0.000000,259.000001,6.953020
2864,51091,VA,Highland,2321.000012,2321.000012,0.000000e+00,100.000000,100.000000,706.699549,738.362185,...,18.000000,0.775528,4.0,0.172340,5.000000,0.215424,0.0,0.000000,17.000000,0.732443
1632,30069,MT,Petroleum,494.000002,494.000002,0.000000e+00,100.000000,100.000000,235.356904,195.160494,...,5.000000,1.012146,0.0,0.000000,0.000000,0.000000,0.0,0.000000,6.000000,1.214575
2738,48431,TX,Sterling,1143.000005,1143.000005,0.000000e+00,100.000000,100.000000,437.321740,540.137198,...,365.000002,31.933508,0.0,0.000000,23.000000,2.012248,0.0,0.000000,92.999999,8.136483
2600,48155,TX,Foard,1336.000005,1336.000005,0.000000e+00,100.000000,100.000000,708.099561,611.490654,...,187.000000,13.997006,5.0,0.374251,3.000000,0.224551,0.0,0.000000,64.000000,4.790419
1696,31085,NE,Hayes,967.000004,967.000004,0.000000e+00,100.000000,100.000000,315.100487,315.013975,...,33.000000,3.412616,3.0,0.310238,2.000000,0.206825,1.0,0.103413,22.000000,2.275078
1616,30037,MT,Golden Valley,884.000003,884.000003,0.000000e+00,100.000000,100.000000,349.824122,373.723578,...,31.000000,3.506787,6.0,0.678733,9.000000,1.018100,0.0,0.000000,38.000000,4.298643
1752,32011,NV,Eureka,1953.428926,1987.000007,1.718572e+00,98.310464,100.000000,494.958120,546.175854,...,238.000001,11.977856,18.0,0.905888,47.000000,2.365375,0.0,0.000000,145.000001,7.297433
275,8061,CO,Kiowa,1398.000005,1398.000005,0.000000e+00,100.000000,100.000000,498.175361,594.555748,...,78.000001,5.579399,0.0,0.000000,7.000000,0.500715,0.0,0.000000,41.000000,2.932761
987,20199,KS,Wallace,486.732735,1485.000005,2.050956e+02,32.776615,100.000000,181.799512,458.745280,...,108.000001,7.272727,1.0,0.067340,7.000000,0.471380,0.0,0.000000,80.000000,5.387205
2702,48359,TX,Oldham,2052.000006,2052.000006,0.000000e+00,100.000000,100.000000,824.215762,708.570609,...,243.000001,11.842105,17.0,0.828460,13.000000,0.633528,0.0,0.000000,110.000001,5.360624
2746,48447,TX,Throckmorton,1641.000004,1641.000004,0.000000e+00,100.000000,100.000000,577.257925,528.665614,...,152.000000,9.262645,7.0,0.426569,12.000000,0.731261,0.0,0.000000,56.000000,3.412553
2792,49031,UT,Piute,1556.000003,1556.000003,0.000000e+00,100.000000,100.000000,638.766843,733.987974,...,108.999999,7.005141,6.0,0.385604,5.000000,0.321337,2.0,0.128535,67.000000,4.305913
1637,30079,MT,Prairie,1179.000002,1179.000002,0.000000e+00,100.000000,100.000000,444.720111,440.484898,...,16.000000,1.357082,6.0,0.508906,2.000000,0.169635,0.0,0.000000,35.000000,2.968617
94,2282,AK,Yakutat,2.522153,662.000001,2.614742e+04,0.380990,100.000000,0.589698,167.845668,...,17.000000,2.567976,27.0,4.078550,236.999998,35.800604,12.0,1.812689,102.999999,15.558912
1661,31015,NE,Boyd,2099.000003,2099.000003,0.000000e+00,100.000000,100.000000,843.723873,865.272503,...,33.000000,1.572177,17.0,0.809909,12.000000,0.571701,2.0,0.095283,32.000000,1.524536
2414,46107,SD,Potter,2329.000003,2329.000003,0.000000e+00,100.000000,100.000000,748.256237,758.046097,...,17.000000,0.729927,8.0,0.343495,20.000000,0.858738,1.0,0.042937,25.000000,1.073422
2545,48045,TX,Briscoe,1637.000002,1637.000002,0.000000e+00,100.000000,100.000000,766.660082,781.575186,...,410.999998,25.106903,0.0,0.000000,3.000000,0.183262,0.0,0.000000,160.000000,9.773977
925,20075,KS,Hamilton,2690.000001,2690.000001,0.000000e+00,100.000000,100.000000,1284.692990,1112.415684,...,827.000001,30.743494,7.0,0.260223,33.000000,1.226766,3.0,0.111524,505.000001,18.773234
928,20081,KS,Haskell,4256.000002,4256.000002,0.000000e+00,100.000000,100.000000,1669.159512,1600.989099,...,1148.999999,26.997180,10.0,0.234962,28.000000,0.657895,0.0,0.000000,565.000001,13.275376
2397,46073,SD,Jerauld,2071.000001,2071.000001,0.000000e+00,100.000000,100.000000,875.104056,645.015626,...,84.000000,4.056012,4.0,0.193143,5.000000,0.241429,3.0,0.144858,49.000000,2.366007
2420,46119,SD,Sully,1373.000000,1373.000000,0.000000e+00,100.000000,100.000000,316.986650,242.168012,...,12.000000,0.873999,0.0,0.000000,16.000000,1.165331,0.0,0.000000,30.000000,2.184996
2395,46069,SD,Hyde,1412.223067,1420.000000,5.506873e-01,99.452329,100.000000,413.099385,270.516747,...,15.000001,1.056338,3.0,0.211268,120.000000,8.450704,1.0,0.070423,30.000000,2.112676
934,20093,KS,Kearny,350.213727,3977.000000,1.035592e+03,8.805978,100.000000,106.814050,1263.293357,...,1135.000002,28.539100,12.0,0.301735,39.000000,0.980639,1.0,0.025145,430.000001,10.812170
2539,48033,TX,Borden,641.000000,641.000000,1.596227e-13,100.000000,100.000000,178.434397,96.197623,...,95.000000,14.820593,1.0,0.156006,2.000000,0.312012,0.0,0.000000,38.000000,5.928237
1649,30103,MT,Treasure,718.000000,718.000000,0.000000e+00,100.000000,100.000000,286.689574,300.031540,...,25.000000,3.481894,3.0,0.417827,6.000000,0.835655,0.0,0.000000,35.000000,4.874652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1941,37103,NC,Jones,0.312788,0.312788,0.000000e+00,0.003081,0.003081,0.124719,0.144903,...,0.011171,0.000110,0.0,0.000000,0.004468,0.000044,0.0,0.000000,0.002234,0.000022
1858,36061,NY,New York,2.000000,2.000000,0.000000e+00,0.000126,0.000126,0.000000,0.000000,...,0.000000,0.000000,2.0,0.000126,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
1045,21105,KY,Hickman,159.003764,0.000000,-1.000000e+02,3.243651,0.000000,61.013072,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
1471,28141,MS,Tishomingo,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
2858,51079,VA,Greene,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
2876,51115,VA,Mathews,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
2456,47057,TN,Grainger,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
548,15005,HI,Kalawao,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
2881,51127,VA,New Kent,0.044135,0.000000,-1.000000e+02,0.000239,0.000000,0.011620,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
2735,48425,TX,Somervell,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
268,8047,CO,Gilpin,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
540,13311,GA,White,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
612,17035,IL,Cumberland,91.845746,NaN,NaN,0.831334,NaN,16.187373,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
754,18115,IN,Ohio,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
777,18161,IN,Union,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1031,21077,KY,Gallatin,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1059,21133,KY,Letcher,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1100,21215,KY,Spencer,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1240,26019,MI,Benzie,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1416,28031,MS,Covington,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1929,37079,NC,Greene,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1950,37121,NC,Mitchell,862.113229,NaN,NaN,5.533816,NaN,397.708173,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2512,47169,TN,Trousdale,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2712,48379,TX,Rains,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2833,51027,VA,Buchanan,1356.810559,NaN,NaN,5.630387,NaN,688.581021,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2845,51051,VA,Dickenson,30.107920,NaN,NaN,0.189322,NaN,17.615772,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2868,51099,VA,King George,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2915,51510,VA,Alexandria,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2926,51610,VA,Falls Church,165.877687,NaN,NaN,1.345100,NaN,10.226877,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3094,55091,WI,Pepin,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<p>So, I need to do some quick math to figure out population, instead of loading another dumb excel file in.</p>

In [14]:
counties["population"] = counties["LACCESS_POP15"] /(counties["PCT_LACCESS_POP15"]/100)

In [15]:
counties_sorted_pop = counties.sort_values("population", ascending=False)
counties_sorted_pop.head(5)

,FIPS,State,County,LACCESS_POP10,LACCESS_POP15,PCH_LACCESS_POP_10_15,PCT_LACCESS_POP10,PCT_LACCESS_POP15,LACCESS_LOWI10,LACCESS_LOWI15,...,PCT_LACCESS_HISP15,LACCESS_NHASIAN15,PCT_LACCESS_NHASIAN15,LACCESS_NHNA15,PCT_LACCESS_NHNA15,LACCESS_NHPI15,PCT_LACCESS_NHPI15,LACCESS_MULTIR15,PCT_LACCESS_MULTIR15,population
204,6037,CA,Los Angeles,613459.048964,622625.436181,1.494213,6.247925,6.341282,139368.943118,161790.521343,...,2.214779,76998.348562,0.784209,3943.964203,0.040168,1399.535435,0.014254,115781.021513,1.179200,9818605.0
610,17031,IL,Cook,415199.839259,373742.394052,-9.984938,7.992797,7.194721,91537.324125,88306.588509,...,0.806436,29637.535941,0.570537,977.220314,0.018812,75.759928,0.001458,22562.511214,0.434339,5194675.0
2623,48201,TX,Harris,886068.668386,740267.412661,-16.454848,21.651253,18.088572,292541.789025,259479.516033,...,6.437218,40101.958015,0.979899,4714.186116,0.115192,690.306606,0.016868,113699.486121,2.778268,4092459.0
103,4013,AZ,Maricopa,492281.154146,511215.572448,3.846261,12.896674,13.392714,139988.257834,167933.017109,...,3.381186,14730.523043,0.385907,10079.040365,0.264049,724.064859,0.018969,73145.345007,1.916246,3817117.0
222,6073,CA,San Diego,456713.537412,424210.884923,-7.116639,14.755003,13.704943,84421.134866,95163.546058,...,2.415206,40484.619297,1.307933,3034.525144,0.098036,1751.033341,0.056570,45842.152590,1.481018,3095313.0

<p>Looks like it worked.<p>

In [16]:
counties_sorted_food_access = counties.sort_values("PCT_LACCESS_POP15", ascending=False)
counties_sorted_food_access.head(5)

,FIPS,State,County,LACCESS_POP10,LACCESS_POP15,PCH_LACCESS_POP_10_15,PCT_LACCESS_POP10,PCT_LACCESS_POP15,LACCESS_LOWI10,LACCESS_LOWI15,...,PCT_LACCESS_HISP15,LACCESS_NHASIAN15,PCT_LACCESS_NHASIAN15,LACCESS_NHNA15,PCT_LACCESS_NHNA15,LACCESS_NHPI15,PCT_LACCESS_NHPI15,LACCESS_MULTIR15,PCT_LACCESS_MULTIR15,population
1712,31117,NE,McPherson,539.000005,539.000005,0.000000e+00,100.000001,100.000001,136.427386,149.300471,...,0.371058,0.0,0.000000,0.000000,0.000000,0.0,0.000000,8.000000,1.484230,539.0
1656,31005,NE,Arthur,460.000004,460.000004,0.000000e+00,100.000001,100.000001,167.370893,202.941179,...,4.130435,1.0,0.217391,2.000000,0.434783,0.0,0.000000,18.000001,3.913044,460.0
72,2068,AK,Denali,1826.000014,1826.000014,0.000000e+00,100.000001,100.000001,338.312491,418.769635,...,2.300110,19.0,1.040526,65.000000,3.559693,1.0,0.054765,94.000000,5.147864,1826.0
567,16033,ID,Clark,982.000006,982.000006,0.000000e+00,100.000001,100.000001,588.970834,641.939249,...,40.529532,5.0,0.509165,10.000000,1.018330,0.0,0.000000,249.000005,25.356416,982.0
1796,35003,NM,Catron,3725.000021,3725.000021,2.685756e-13,100.000001,100.000001,1664.513780,1693.913842,...,19.033557,7.0,0.187919,99.000001,2.657718,0.0,0.000000,259.000001,6.953020,3725.0

<p>Now we'll look at food insecurity in the top decile of U.S. counties.</p>
<p>We can tweak this later if we want to look at the top quartile, and reuse this process to look at large census tracts (though, if you understand census tracts, won't really mean much.)</p>

In [17]:
counties_sorted_food_access_top_10_poppercent = counties_sorted_food_access["population"].quantile(q=0.9)

In [20]:
big_counties = counties_sorted_food_access[counties_sorted_food_access["population"] >= counties_sorted_food_access_top_10_poppercent]

In [22]:
big_counties.head(5)

,FIPS,State,County,LACCESS_POP10,LACCESS_POP15,PCH_LACCESS_POP_10_15,PCT_LACCESS_POP10,PCT_LACCESS_POP15,LACCESS_LOWI10,LACCESS_LOWI15,...,PCT_LACCESS_HISP15,LACCESS_NHASIAN15,PCT_LACCESS_NHASIAN15,LACCESS_NHNA15,PCT_LACCESS_NHNA15,LACCESS_NHPI15,PCT_LACCESS_NHPI15,LACCESS_MULTIR15,PCT_LACCESS_MULTIR15,population
1217,25001,MA,Barnstable,108706.072108,104445.410707,-3.919433,50.352994,48.379442,18588.411553,20979.404615,...,0.910748,1005.382658,0.465696,609.254256,0.282208,30.365998,0.014066,3300.833662,1.528957,215888.0
104,4015,AZ,Mohave,88373.508832,88341.577129,-0.036133,44.145699,44.129748,34539.671598,40061.481981,...,5.874096,769.304758,0.384295,1751.832051,0.875102,147.264868,0.073564,6700.216554,3.346996,200186.0
1781,34015,NJ,Gloucester,126342.999249,126082.686590,-0.206036,43.825272,43.734976,23070.197740,25220.882404,...,2.186748,3381.042017,1.172800,226.031845,0.078405,29.385861,0.010193,4712.994993,1.634822,288288.0
650,17111,IL,McHenry,133010.885184,133295.441456,0.213935,43.079053,43.171214,19724.203679,21858.325964,...,4.439097,3971.716593,1.286344,424.093169,0.137354,31.278624,0.010130,7281.580725,2.358330,308760.0
1788,34029,NJ,Ocean,281416.744260,248325.574735,-11.758778,48.809027,43.069682,59216.727160,51963.867805,...,2.949509,4251.112803,0.737315,337.356020,0.058511,44.667797,0.007747,7807.931421,1.354211,576567.0

<p>Now let's just look at the columns we need then output the data for Lisa!</p>

In [23]:
final_counties = big_counties[["State", "County", "PCT_LACCESS_POP15"]]

In [27]:
final_counties.rename(columns={"PCT_LACCESS_POP15": "percent_without_grocery_access"}).head()

     State      County  percent_without_grocery_access
1217    MA  Barnstable                       48.379442
104     AZ      Mohave                       44.129748
1781    NJ  Gloucester                       43.734976
650     IL     McHenry                       43.171214
1788    NJ       Ocean                       43.069682

In [29]:
final_counties = final_counties.rename(columns={"PCT_LACCESS_POP15": "percent_without_grocery_access"})

In [25]:
len(final_counties)

312

In [32]:
final_counties.to_csv("output/final_counties.csv")

### Now let's do some similar analyses for Census tracts

In [59]:
tract_variables.head(50)

,Field,LongName,Description
0,CensusTract,Census tract,Census tract number
1,State,State,State name
2,County,County,County name
3,Urban,Urban tract,Flag for urban tract
4,POP2010,"Population, tract total",Population count from 2010 census
5,OHU2010,"Housing units, total",Occupied housing unit count from 2010 census
6,GroupQuartersFlag,"Group quarters, tract with high share",Flag for tract where >=67%
7,NUMGQTRS,"Group quarters, tract population residing in, ...",Count of tract population residing in group qu...
8,PCTGQTRS,"Group quarters, tract population residing in, ...",Percent of tract population residing in group ...
9,LILATracts_1And10,Low income and low access tract measured at 1 ...,Flag for food desert when considering low acce...
10,LILATracts_halfAnd10,Low income and low access tract measured at 1/...,Flag for food desert when considering low acce...
11,LILATracts_1And20,Low income and low access tract measured at 1 ...,Flag for food desert when considering low acce...
12,LILATracts_Vehicle,Low income and low access tract using vehicle ...,Flag for food desert when considering vehicle ...
13,HUNVFlag,"Vehicle access, tract with low vehicle access",Flag for tract where >= 100 of households do n...
14,LowIncomeTracts,Low income tract,Flag for low income tract
15,PovertyRate,Tract poverty rate,Share of the tract population living with inco...
16,MedianFamilyIncome,Tract median family income,Tract median family income
17,LA1and10,Low access tract at 1 mile for urban areas and...,Flag for low access tract at 1 mile for urban ...
18,LAhalfand10,Low access tract at 1/2 mile for urban areas a...,Flag for low access tract at 1/2 mile for urba...
19,LA1and20,Low access tract at 1 mile for urban areas and...,Flag for low access tract at 1 mile for urban ...
20,LATracts_half,Low access tract at 1/2 mile,Flag for low access tract when considering 1/2...
21,LATracts1,Low access tract at 1 mile,Flag for low access tract when considering 1 m...
22,LATracts10,Low access tract at 10 miles,Flag for low access tract when considering 10 ...
23,LATracts20,Low access tract at 20 miles,Flag for low access tract when considering 20 ...
24,LATractsVehicle_20,Low access tract using vehicle access and at 2...,Flag for tract where >= 100 of households do n...
25,LAPOP1_10,"Low access, population at 1 mile for urban are...",Population count beyond 1 mile for urban areas...
26,LAPOP05_10,"Low access, population at 1/2 mile for urban a...",Population count beyond 1/2 mile for urban are...
27,LAPOP1_20,"Low access, population at 1 mile for urban are...",Population count beyond 1 mile for urban areas...
28,LALOWI1_10,"Low access, low-income population at 1 mile fo...",Low income population count beyond 1 mile for ...
29,LALOWI05_10,"Low access, low-income population at 1/2 mile ...",Low income population count beyond 1/2 mile fo...
30,LALOWI1_20,"Low access, low-income population at 1 mile fo...",Low income population count beyond 1 mile for ...
31,lapophalf,"Low access, population at 1/2 mile, number",Population count beyond 1/2 mile from supermarket
32,lapophalfshare,"Low access, population at 1/2 mile, share",Share of tract population that are beyond 1/2 ...
33,lalowihalf,"Low access, low-income population at 1/2 mile,...",Low income population count beyond 1/2 mile fr...
34,lalowihalfshare,"Low access, low-income population at 1/2 mile,...",Share of tract population that are low income ...
35,lakidshalf,"Low access, children age 0-17 at 1/2 mile, number",Kids population count beyond 1/2 mile from sup...
36,lakidshalfshare,"Low access, children age 0-17 at 1/2 mile, share",Share of tract population that are kids beyond...
37,laseniorshalf,"Low access, seniors age 65+ at 1/2 mile, number",Seniors population count beyond 1/2 mile from ...
38,laseniorshalfshare,"Low access, seniors age 65+ at 1/2 mile, share",Share of tract population that are seniors bey...
39,lawhitehalf,"Low access, White population at 1/2 mile, number",White population count beyond 1/2 mile from su...
40,lawhitehalfshare,"Low access, White population at 1/2 mile, share",Share of tract population that are white beyon...
41,lablackhalf,"Low access, Black or African American populati...",Black or African American population count bey...
42,lablackhalfshare,"Low access, Black or African American populati...",Share of tract population that are Black or Af...
43,laasianhalf,"Low access, Asian population at 1/2 mile, number",Asian population count beyond 1/2 mile from su...
44,laasianhalfshare,"Low access, Asian population at 1/2 mile, share",Share of tract population that are Asian beyon...
45,lanhopihalf,"Low access, Native Hawaiian or Other Pacific I...",Native Hawaiian or Other Pacific Islander popu...
46,lanhopihalfshare,"Low access, Native Hawaiian or Other Pacific I...",Share of tract population that are Native Hawa...
47,laaianhalf,"Low access, American Indian or Alaska Native p...",American Indian or Alaska Native population co...
48,laaianhalfshare,"Low access, American Indian or Alaska Native p...",Share of tract population that are American In...
49,laomultirhalf,"Low access, Other/Multiple race population at ...",Other/Multiple race population count beyond 1/...

In [80]:
urban_tracts = tracts[tracts["Urban"] == 1]
rural_tracts = tracts[tracts["Urban"] == 0]

In [81]:
urban_tracts = urban_tracts[["CensusTract", "County", "lapop1", "lapop1share"]]

In [82]:
urban_tracts.sort_values("lapop1", ascending=False)

       CensusTract           County        lapop1  lapop1share
18028  12115002712         Sarasota  28169.962643     0.852576
63492  48157673101        Fort Bend  18853.562690     0.567861
18137  12119911200           Sumter  18357.345261     0.618571
66040  48439114103          Tarrant  17711.605877     0.878378
16917  12097041100          Osceola  16827.000220     1.000000
63509  48157674502        Fort Bend  16661.587439     0.993713
9107    6071009118   San Bernardino  15860.657628     0.693756
30799  24033807200  Prince George's  15632.146611     0.981056
63488  48157672900        Fort Bend  15599.258076     0.546633
53205  39165031903           Warren  15578.414890     0.966763
40593  34001011802         Atlantic  15577.197517     0.988087
19555  13135050608         Gwinnett  15229.323101     0.987506
24445  18063210102        Hendricks  15163.230173     0.933352
20637  16001010313              Ada  14763.246205     0.768759
19683  13153021113          Houston  14761.434198     0.827388
17743  12105012503             Polk  14622.907100     0.936525
19359  13121010510           Fulton  14582.437492     0.920550
9102    6071009110   San Bernardino  14573.702618     0.935531
16891  12095017802           Orange  14238.244858     0.999035
63549  48167720503        Galveston  14006.999900     1.000000
66233  48453001760           Travis  13991.473458     0.981445
64523  48201555502           Harris  13972.289491     0.821127
65253  48339690402       Montgomery  13914.916280     0.881751
19353  13121010301           Fulton  13778.597829     0.897629
17938  12113010811       Santa Rosa  13430.593332     0.988343
19573  13135050728         Gwinnett  13328.343942     0.944603
64509  48201554801           Harris  12971.476505     0.921531
66280  48453001841           Travis  12756.372472     0.773348
59524  45079010103         Richland  12744.296509     0.742891
64688  48215024112          Hidalgo  12662.999956     1.000000
...            ...              ...           ...          ...
44180  36047004500            Kings      0.000000     0.000000
44179  36047004400            Kings      0.000000     0.000000
44178  36047004300            Kings      0.000000     0.000000
44201  36047006800            Kings      0.000000     0.000000
44202  36047006900            Kings      0.000000     0.000000
44203  36047007000            Kings      0.000000     0.000000
44217  36047009000            Kings      0.000000     0.000000
44227  36047010800            Kings      0.000000     0.000000
44226  36047010600            Kings      0.000000     0.000000
44225  36047010400            Kings      0.000000     0.000000
44224  36047010200            Kings      0.000000     0.000000
44223  36047010100            Kings      0.000000     0.000000
44222  36047010000            Kings      0.000000     0.000000
44221  36047009800            Kings      0.000000     0.000000
44220  36047009600            Kings      0.000000     0.000000
44219  36047009400            Kings      0.000000     0.000000
44218  36047009200            Kings      0.000000     0.000000
44216  36047008800            Kings      0.000000     0.000000
44204  36047007100            Kings      0.000000     0.000000
44214  36047008500            Kings      0.000000     0.000000
44213  36047008400            Kings      0.000000     0.000000
44212  36047008200            Kings      0.000000     0.000000
44211  36047008000            Kings      0.000000     0.000000
44210  36047007800            Kings      0.000000     0.000000
44209  36047007700            Kings      0.000000     0.000000
44208  36047007600            Kings      0.000000     0.000000
44207  36047007500            Kings      0.000000     0.000000
44206  36047007400            Kings      0.000000     0.000000
44205  36047007200            Kings      0.000000     0.000000
46140  36075021601           Oswego      0.000000     0.000000

[55172 rows x 4 columns]

In [1]:
rural_tracts = rural_tracts[["CensusTract", "County", "lapop10", "lapop10share"]]

NameError: name 'rural_tracts' is not defined

In [85]:
rural_tracts.sort_values("lapop10", ascending=False)

       CensusTract          County      lapop10  lapop10share
1237    2050000100          Bethel  8926.325945      0.941298
8509    6065981000       Riverside  7634.000239      1.000000
61470  48001950402        Anderson  7534.999916      1.000000
1352    4001944300          Apache  6657.126418      0.956759
18292  12133970302      Washington  6608.643589      0.999039
43652  36019100400         Clinton  6391.244914      0.866257
29364  22125951701  West Feliciana  6097.247074      0.737095
1349    4001944100          Apache  5869.090739      0.999845
40060  32003007500           Clark  5810.423905      0.920245
42864  35031946000        McKinley  5656.982464      0.996474
1347    4001942700          Apache  5628.000015      1.000000
4514    6025012301        Imperial  5623.410052      0.998298
29099  22079013500         Rapides  5608.404998      0.898351
37292  28135950300    Tallahatchie  5453.001452      0.998901
20277  15001021202          Hawaii  5354.220895      0.633561
2381    4015950600          Mohave  5283.188143      0.585135
62029  48039661900        Brazoria  5283.145764      0.431172
1319    2180000100            Nome  5253.940628      0.917719
2415    4015954800          Mohave  5247.201988      0.748317
48988  37095920100            Hyde  5226.823353      0.899625
2285    4013723306        Maricopa  5224.997977      0.993535
2759    4021002200           Pinal  5220.310677      0.994345
3251    5091021000          Miller  5079.316818      0.629954
20833  16063950100         Lincoln  5074.030993      0.974276
71624  55031030100         Douglas  5047.050024      0.807916
12246   8041003909         El Paso  5029.594899      0.769640
68403  51135000300        Nottoway  5001.970290      0.708093
66384  48457950400           Tyler  4927.067109      0.919400
71215  54077963800         Preston  4889.802688      0.723023
29072  22079010100         Rapides  4882.717042      0.526950
...            ...             ...          ...           ...
34042  26125122700         Oakland     0.000000      0.000000
34044  26125123000         Oakland     0.000000      0.000000
34045  26125123100         Oakland     0.000000      0.000000
34046  26125124000         Oakland     0.000000      0.000000
34014  26121003500        Muskegon     0.000000      0.000000
34013  26121003400        Muskegon     0.000000      0.000000
34012  26121003300        Muskegon     0.000000      0.000000
34010  26121003100        Muskegon     0.000000      0.000000
33956  26115833500          Monroe     0.000000      0.000000
33957  26115833600          Monroe     0.000000      0.000000
33958  26115833700          Monroe     0.000000      0.000000
33961  26115990000          Monroe     0.000000      0.000000
33962  26117970100        Montcalm     0.000000      0.000000
33963  26117970200        Montcalm     0.000000      0.000000
33964  26117970300        Montcalm     0.000000      0.000000
33965  26117970400        Montcalm     0.000000      0.000000
33966  26117970500        Montcalm     0.000000      0.000000
33967  26117970600        Montcalm     0.000000      0.000000
33968  26117970700        Montcalm     0.000000      0.000000
33969  26117970800        Montcalm     0.000000      0.000000
33970  26117970900        Montcalm     0.000000      0.000000
33971  26117971000        Montcalm     0.000000      0.000000
33972  26117971100        Montcalm     0.000000      0.000000
33974  26117971300        Montcalm     0.000000      0.000000
33978  26119910400     Montmorency     0.000000      0.000000
33979  26119910500     Montmorency     0.000000      0.000000
33993  26121001600        Muskegon     0.000000      0.000000
34008  26121002900        Muskegon     0.000000      0.000000
34009  26121003000        Muskegon     0.000000      0.000000
38651  29225470301         Webster     0.000000      0.000000

[17692 rows x 4 columns]